### ISSUE TITLE
Query database so it outputs entries in chronological order

### ISSUE THREAD

**Issue by OscarSLi** [OscarSLi/deer#12]
This may be difficult because we are already querying the database so that it outputs entries sorted by location.

**Comment by delimited0** [comment]
Also we're depending on location sorting for plotting multiple events at the same location.

**Comment by OscarSLi** [comment]
Yeah, what I was thinking was the pass two separate MySQL tables to the frontend, one sorted by location and the other sorted by chronological order. This will require a bit of change our current structure of index.js
